-- ==========================================
-- SCRIPT DE INICIALIZACION MAESTRO (NEON)
-- ==========================================
-- Este script inicializa la base de datos compartida para:
-- 1. AbTech Backend (CRM) -> Schema 'abtech'
-- 2. BarberShop Backend (App) -> Schema 'barbershop'

-- ------------------------------------------
-- 1. SCHEMAS
-- ------------------------------------------
CREATE SCHEMA IF NOT EXISTS "abtech";
CREATE SCHEMA IF NOT EXISTS "barbershop";

-- ------------------------------------------
-- 2. SCHEMA: ABTECH (CRM)
-- ------------------------------------------
SET search_path TO "abtech";

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    role VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    fullName VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    message VARCHAR(255),
    industry VARCHAR(255),
    source VARCHAR(255),
    status VARCHAR(255),
    notes TEXT,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    company VARCHAR(255),
    status VARCHAR(255),
    createdAt TIMESTAMP
);

-- ------------------------------------------
-- 3. SCHEMA: BARBERSHOP (APP)
-- ------------------------------------------
SET search_path TO "barbershop";

-- Tabla: USERS
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) -- Enum: USER, ADMIN, BARBER
);

-- Tabla: BARBERS
CREATE TABLE IF NOT EXISTS barbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    photoUrl VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    user_id BIGINT,
    CONSTRAINT fk_barber_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Tabla: APPOINTMENT_TYPES
CREATE TABLE IF NOT EXISTS appointment_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    price DOUBLE PRECISION,
    durationMinutes INTEGER,
    color VARCHAR(50)
);

-- Tabla: APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    barber_id BIGINT,
    appointment_type_id BIGINT,
    startTime TIMESTAMP,
    endTime TIMESTAMP NOT NULL,
    status VARCHAR(50), -- Enum: BOOKED, COMPLETED, CANCELLED
    guestName VARCHAR(255),
    guestEmail VARCHAR(255),
    guestPhone VARCHAR(255),
    notes TEXT,
    CONSTRAINT fk_appointment_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_appointment_barber FOREIGN KEY (barber_id) REFERENCES barbers(id),
    CONSTRAINT fk_appointment_type FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id)
);

-- 4. Confirmación
SELECT 'Base de datos inicializada correctamente para AbTech y BarberShop' as mensaje;
