package com.abtech.backend;

import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import com.abtech.backend.model.ERole;
import com.abtech.backend.model.User;
import com.abtech.backend.repository.UserRepository;

@Component
public class DataInitializer implements CommandLineRunner {

    @Autowired
    UserRepository userRepository;

    @Autowired
    PasswordEncoder encoder;

    @Autowired
    javax.sql.DataSource dataSource;

    @Override
    public void run(String... args) throws Exception {
        // Create Schemas for Tenants (Hack for H2/Demo)
        // Create Schemas for Tenants (Hack for H2/Demo)
        /*
         * try (java.sql.Connection conn = dataSource.getConnection();
         * java.sql.Statement stmt = conn.createStatement()) {
         * stmt.execute("CREATE SCHEMA IF NOT EXISTS \"abtech\"");
         * stmt.execute("CREATE SCHEMA IF NOT EXISTS \"barbershop\"");
         * 
         * // Create Tables (Hack for Demo - Hibernate doesn't auto-create for
         * // multi-schema)
         * String createTableLeadsSql = "CREATE TABLE IF NOT EXISTS leads (" +
         * "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
         * "name VARCHAR(255), " +
         * "fullName VARCHAR(255), " +
         * "phone VARCHAR(255), " +
         * "email VARCHAR(255), " +
         * "message VARCHAR(255), " +
         * "industry VARCHAR(255), " +
         * "source VARCHAR(255), " +
         * "status VARCHAR(255), " +
         * "notes TEXT, " +
         * "createdAt TIMESTAMP, " +
         * "updatedAt TIMESTAMP)";
         * 
         * String createTableClientsSql = "CREATE TABLE IF NOT EXISTS clients (" +
         * "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
         * "name VARCHAR(255) NOT NULL, " +
         * "email VARCHAR(255) NOT NULL, " +
         * "phone VARCHAR(255), " +
         * "company VARCHAR(255), " +
         * "status VARCHAR(255), " +
         * "createdAt TIMESTAMP)";
         * 
         * stmt.execute("SET SCHEMA \"abtech\"");
         * stmt.execute(createTableLeadsSql);
         * stmt.execute(createTableClientsSql);
         * 
         * stmt.execute("SET SCHEMA \"barbershop\"");
         * stmt.execute(createTableLeadsSql);
         * stmt.execute(createTableClientsSql);
         * 
         * System.out.
         * println(">>> SCHEMAS AND TABLES FOR 'abtech' AND 'barbershop' CHECKED/CREATED."
         * );
         * }
         */

        // Check if admin exists
        if (!userRepository.existsByUsername("admin")) {
            User admin = new User("admin", "admin@abtech.com", encoder.encode("123456"));
            admin.setRole(ERole.ROLE_ADMIN);
            userRepository.save(admin);
            System.out.println(">>> ADMIN USER CREATED: Username: 'admin', Password: '123456'");
        }
    }
}
