-- Ensure tables exist in PUBLIC schema (PostgreSQL)
-- Explicitly force PUBLIC prefix to avoid "no schema selected" error
CREATE SCHEMA IF NOT EXISTS "public";
SET search_path TO "public";

CREATE TABLE IF NOT EXISTS "public".app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(120) NOT NULL,
    role VARCHAR(20),
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS "public".clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    company VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "public".leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    full_name VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    message VARCHAR(255),
    industry VARCHAR(255),
    source VARCHAR(255),
    status VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);
